### ISSUE TITLE
Replacing temporary file within a context manager causes failure

### ISSUE THREAD

**Issue by tashrifbillah** [AMP-SCZ/lochness#129]
`os.rename` did not work when we changed the TMPDIR to `/mnt/ProNET/newtmp`. So we replaced it with `os.replace`

https://github.com/AMP-SCZ/lochness/blob/fa04f6d5add2c73ebe7e9efa95de2d99b9bd738d/lochness/__init__.py#L594

If this solution is found stable, we shall commit it to kcho/pronet branch.

---

Edit:

`os.replace` was found to be ineffectual.

**Comment by tashrifbillah** [comment]
Within this context manager, a temporary file is created:

https://github.com/AMP-SCZ/lochness/blob/fa04f6d5add2c73ebe7e9efa95de2d99b9bd738d/lochness/redcap/__init__.py#L121-L124

Then this tries to replace that temporary file with a second temporary file:

https://github.com/AMP-SCZ/lochness/blob/fa04f6d5add2c73ebe7e9efa95de2d99b9bd738d/lochness/__init__.py#L580-L594

This cannot be a good design. After we set `TMPDIR` environment variable, the Lochness program fails at these two lines.

**Comment by tashrifbillah** [comment]
So we removed dependency on the nested context manager/temporary file and wrote `content` directly to the first temporary file:

```python
 with tf.NamedTemporaryFile(suffix='tmp.json') as tmpfilename: 
     # lochness.atomic_write(tmpfilename.name, content)
     with open(tmpfilename.name, 'w') as f: 
         f.write(content.decode('utf-8')
         f.flush()

     with open(tmpfilename.name, 'r') as f: 
         data = json.load(f) 
```

This 'direct' approach solved our current issue and is running Lochness now.

**Comment by dheshanm** [comment]
Traceback showing FileNotFoundError: [Errno 2]

```
Traceback (most recent call last):                                                                                                                                                                                 
  File "/opt/software/lochness/lochness/redcap/__init__.py", line 122, in initialize_metadata                                                                                                                      
    lochness.atomic_write(tmpfilename.name, content)                                                                                                                                                               
  File "/opt/software/lochness/lochness/__init__.py", line 599, in atomic_write                                                                                                                                    
    os.replace(tmp.name, filename)                                                                                                                                                                                 
FileNotFoundError: [Errno 2] No such file or directory: '/mnt/ProNET/newtmp/.7fh0thez' -> '/mnt/ProNET/newtmp/tmploo_5t34tmp.json'                                                                                 
                                                                                                                                                                                                                   
During handling of the above exception, another exception occurred:                                                                                                                                                
                                                                                                                                                                                                                   
Traceback (most recent call last):                                                                                                                                                                                 
  File "/opt/software/lochness/scripts/sync.py", line 289, in <module>                                                                                                                                             
    main()                                                                                                                                                                                                         
  File "/opt/software/lochness/scripts/sync.py", line 159, in main                                                                                                                                                 
    do(args, Lochness)                                                                                                                                                                                             
  File "/opt/software/lochness/scripts/sync.py", line 222, in do                                                                                                                                                   
    lochness.initialize_metadata(Lochness, args,                                                                                                                                                                   
  File "/opt/software/lochness/lochness/__init__.py", line 104, in initialize_metadata                                                                                                                             
    REDCap.initialize_metadata(                                                                                                                                                                                    
  File "/opt/software/lochness/lochness/redcap/__init__.py", line 124, in initialize_metadata                                                                                                                      
    data = json.load(f)                                                                                                                                                                                            
  File "/opt/software/miniconda3/lib/python3.8/tempfile.py", line 492, in __exit__                                                                                                                                 
    self.close()                                                                                                                                                                                                   
  File "/opt/software/miniconda3/lib/python3.8/tempfile.py", line 499, in close                                                                                                                                    
    self._closer.close()                                                                                                                                                                                           
  File "/opt/software/miniconda3/lib/python3.8/tempfile.py", line 436, in close                                                                                                                                    
    unlink(self.name)                                                                                                                                                                                              
FileNotFoundError: [Errno 2] No such file or directory: '/mnt/ProNET/newtmp/tmploo_5t34tmp.json'
```

**Comment by tashrifbillah** [comment]
[This](https://github.com/AMP-SCZ/lochness/issues/129#issuecomment-1779576733) solves the error in only one place. But `atomic_write()` is used in other places in Lochness too. To cover all of them, Tashrif commented out [this](https://github.com/AMP-SCZ/lochness/blob/fa04f6d5add2c73ebe7e9efa95de2d99b9bd738d/lochness/__init__.py#L580-L594) block and inserted:

```python
with open(filename,'w') as f:
  f.write(content.decoding(encoding))
  f.flush()
```
