### ISSUE TITLE
Note about lochness_sync_history_csv in configuration_file.rst

### ISSUE THREAD

**Issue by tashrifbillah** [AMP-SCZ/lochness#28]
Should we add documentation for `lochness_sync_history_csv` in https://github.com/PREDICT-DPACC/lochness/blob/master/docs/source/configuration_file.rst:

I used my old configuration file and ran into the error:
```
Traceback (most recent call last):
  File "/home/tb571/min3-dpdash/bin/sync.py", line 154, in <module>
    main()
  File "/home/tb571/min3-dpdash/bin/sync.py", line 120, in main
    do(args)
  File "/home/tb571/min3-dpdash/bin/sync.py", line 150, in do
    lochness_to_lochness_transfer(Lochness)
  File "/home/tb571/min3-dpdash/lib/python3.8/site-packages/lochness/transfer/__init__.py", line 220, in lochness_to_lochness_transfer
    compress_new_files(Lochness['lochness_sync_history_csv'],
KeyError: 'lochness_sync_history_csv'
```

**Comment by kcho** [comment]
Great point.

Added here.
https://github.com/PREDICT-DPACC/lochness/pull/27/commits/8abc1839b59ae16b5d9cd9f2a9f1381a7aa4009f
