### ISSUE TITLE
lock_lochness() got an unexpected keyword argument 'pii_table_loc'

### ISSUE THREAD

**Issue by tashrifbillah** [AMP-SCZ/lochness#45]
I am investigating already but if you know a quicker fix:

```bash
2021-09-17 10:36:53,295 - 38513 - lochness.redcap - DEBUG - saving /data/predict/tb571_lochness_tes                    t/RED-PHOENIX/PROTECTED/FAKE_AD/raw/YA99274/surveys/YA99274.FAKE_AD.json
Traceback (most recent call last):
  File "/home/tb571/miniconda3/bin/sync.py", line 176, in <module>
    main()
  File "/home/tb571/miniconda3/bin/sync.py", line 132, in main
    do(args, Lochness)
  File "/home/tb571/miniconda3/bin/sync.py", line 163, in do
    dpanonymize.lock_lochness(Lochness, pii_table_loc=Lochness['pii_table'])
TypeError: lock_lochness() got an unexpected keyword argument 'pii_table_loc'
```
It is coming from:
https://github.com/AMP-SCZ/lochness/blob/d67839878f991eb7e71ebacec8777d8d0ad7b8ad/scripts/sync.py#L164

It is strange because the current dpanonymize master is programmed to accept kwargs:

https://github.com/AMP-SCZ/dpanonymize/blob/49282b5c67ca1f88e7a651bc724e639b97e819d9/dpanonymize/__init__.py#L149

@kcho

**Comment by tashrifbillah** [comment]
Okay found the reason:

https://github.com/AMP-SCZ/lochness/blob/d67839878f991eb7e71ebacec8777d8d0ad7b8ad/setup.py#L18

installs the PyPi hosted release which probably has not been updated to reflect the current dpanonymize. This is not worth our time. We should just install the current master.
